<?php echo $this->getChildHtml('header') ?>
<div class="main-container col1-layout">
    <div class="main">
        <?php echo $this->getChildHtml('breadcrumbs') ?>
        <div class="col-main">
            <?php echo $this->getChildHtml('content') ?>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
